### ISSUE TITLE
Question on OTA updates for 2023.02.07.0-19 and beyond

### ISSUE THREAD

**Issue by iMacheist** [NebraLtd/helium-syncrobit#11]
Is anyone on 2023.02.07.0-19 getting OTA updates? Mine was updated to -19 OTA and has been dead since with no OTA. Is a flash necessary to the latest update needed?

**Comment by shawaj** [comment]
Yes you will need to reflash I'm afraid.

See the comment here for more info...
https://github.com/NebraLtd/helium-syncrobit/issues/2#issuecomment-1482037237

**Comment by shawaj** [comment]
Once you are on one of those newer images you will get the OTA updates so won't need to reflash after that
