### ISSUE TITLE
Bad snr 2023.02.07.0-25 (c165b61)

### ISSUE THREAD

**Issue by Dani1914** [NebraLtd/helium-syncrobit#12]
Latest update haved bad snr,for example same withnes in frimware v16 haved snr -5 and in latest frimware v25 the snr -15!All whithnes same situation!with bad snr i resived minus whithnes!Version 16 its two much bether!
B.r .

**Comment by shawaj** [comment]
The concentrator settings haven't changed. So this is not due to our codebase
