### ISSUE TITLE
Been offline for 3 days inactive. 2023.02.07.0-25-helium-syncrobit-2023-03-27

### ISSUE THREAD

**Issue by TheCryptoMoe** [NebraLtd/helium-syncrobit#14]
Been offline for the passed 3 days, tried the latest firmware as well as the version before the latest, the old one caused the syncrobit not to even boot, this one boots but no one activity or witnesses.

**Comment by shawaj** [comment]
You are probably affected by #2 most likely.

What does diagnostics page show?

**Comment by TheCryptoMoe** [comment]
unfortunately my Syncrobit's information literally faded out from the back of the unit and I cannot log into the nebra support for anything... its pretty crappy but I know its connected as the lights are solid, not flashing like as if the SD card has an error being read!

**Comment by shawaj** [comment]
You can probably find the Mac address from your router.

Alternatively, you can get it by adding the device to balenaCloud and getting the device details from there

Alternatively just plug the SD card or CM4 (if it has onboard EMMC) into your computer, look in the resin-boot volume, and look for a file called config.json

Inside there will be a UUID number.

If you share that we can tell you the Mac address and serial number of the device 🙌

**Comment by rpvrpv** [comment]
I also have issues again.

![image](https://user-images.githubusercontent.com/128090615/228432815-d7f3d8ad-6511-41b0-81fb-68a6a86b8f19.jpeg)

**Comment by rpvrpv** [comment]
I can send you the support file if you want/need? Or here as text...


{"AN":"bitter-onyx-rhino","BA":"HELIUM-SYNCROBIT","BALENA_DEVICE_TYPE":["raspberrypicm4-ioboard"],"BN":"black-turnip","BT":true,"BUTTON":27,"CELLULAR":false,"CONTAINS_FCC_IDS":[],"CONTAINS_IC_IDS":[],"CPU_ARCH":"arm64","E0":"E4:5F:01:32:70:99","ECC":true,"ECCOB":true,"FCC_IDS":[],"FR":"N/A (Non Nebra Miner)","FRIENDLY":"Syncrobit Hotspot","FW":"2023.02.07.0-26","IC_IDS":[],"ID":"6b559e98dcd092092f1dc920bb402206","LOR":true,"LTE":false,"MAC":"wlan0","OK":"112rfXQ8YPWN8LWY1e7upY3FnvwAwJLcWfpLnf4SLzSYgjiPqwwj","ONBOARDING_KEY_URI":["ecc://i2c-1:96?slot=0","ecc://i2c-1:88?slot=15"],"PF":true,"PK":"112rfXQ8YPWN8LWY1e7upY3FnvwAwJLcWfpLnf4SLzSYgjiPqwwj","RE":"EU868","RESET":17,"SPIBUS":"spidev0.0","STATUS":22,"SUPPORTED_MODELS":["Syncrobit Hotspot"],"SWARM_KEY_URI":["ecc://i2c-1:96?slot=0","ecc://i2c-1:88?slot=2"],"TYPE":"Full","VA":"COMP-SYNCROBITCM4","W0":"E4:5F:01:32:70:9A","firmware_short_hash":"7784b16","last_updated":"05:08 UTC 29 Mar 2023","serial_number":"100000003b896cc4"}

**Comment by TheCryptoMoe** [comment]
Thank you bro sorry for the double post here! I just installed the new firmware, ill definitely do this on the next firmware update, Just got home from work and Barely have the energy to stay up lol. thx again and good work in here! I know ya'll dont get the praise you deserve!

**Comment by TheCryptoMoe** [comment]
Syncrobit Up & Running after latest firmware! GOD BLESS THE DEV!

**Comment by shawaj** [comment]
@rpvrpv yours is earning... https://explorer.helium.com/hotspots/112rfXQ8YPWN8LWY1e7upY3FnvwAwJLcWfpLnf4SLzSYgjiPqwwj

**Comment by shawaj** [comment]
> Syncrobit Up & Running after latest firmware! GOD BLESS THE DEV!

Thanks @TheCryptoMoe - I've shared this message with our entire dev team @NebraLtd/developers as they all deserve praise.

If you have found this software beneficial we would be super grateful for any sponsorship at https://github.com/sponsors/NebraLtd

Alternatively, if you don't want to sponsor, just praising us on Discord, Reddit and other places will be great! And also we would love to receive some 5 star reviews via [Trustpilot](https://uk.trustpilot.com/review/nebra.com) and [Google](https://g.co/kgs/Ka68xk)

I'll close this issue for now, but feel free to open another in the future if you have any further issues.

**Comment by TheCryptoMoe** [comment]
> You can probably find the Mac address from your router.
> 
> Alternatively, you can get it by adding the device to balenaCloud and getting the device details from there
> 
> Alternatively just plug the SD card or CM4 (if it has onboard EMMC) into your computer, look in the resin-boot volume, and look for a file called config.json
> 
> Inside there will be a UUID number.
> 
> If you share that we can tell you the Mac address and serial number of the device 🙌

brother, 
UUID =
fe3b12799dd522af0bfd233584719d8b
Can you DM Mm by any chance on here?
