### ISSUE TITLE
After recent update helium-syncrobit-2023-03-28 24 hours later Miner went offline

### ISSUE THREAD

**Issue by TheCryptoMoe** [NebraLtd/helium-syncrobit#15]
Hey guys, did the new firmware update, flashed, everything went back to normal, today when I Got home i noticed the syncro flashing quickly 3x then back to solid red, which means their is a problem with the SD card.

Removed it, reflashed it, and put it back in, all back online now but for how long? What could be the issue ? is it lack of space on the sd card? Should i upgrade from a 32 to a 64gb?

**Comment by shawaj** [comment]
It will be unlikely to use more than 4 GB ever. As they don't sync the blockchain anymore.

It's probably just that the SD card didn't flash properly.

Also, you don't need to reflash every time there is an update. They will automatically pull in the new updates over the air.
