### ISSUE TITLE
Latest update has my miner dead

### ISSUE THREAD

**Issue by Dmoss1976** [NebraLtd/helium-syncrobit#21]
I recently acquired a new syncrobit miner that I have transfered and asserted, however since updating to this latest version the miner isn't doing anything. No beacons no witness nothing. Any ideas?

**Comment by shawaj** [comment]
Where did you get the image from and how did you program it?

**Comment by Dmoss1976** [comment]
i downloaded it from here and used Rasberry Pi Imager. when I log into the devices IP address it just says Error Status

**Comment by shawaj** [comment]
Can you try Balena Etcher. And also please make sure to verify the md5 checksum to ensure the download wasn't corrupted.

This release is working fine on thousands of Syncrobit devices

**Comment by shawaj** [comment]
This was the image you downloaded? https://github.com/NebraLtd/helium-syncrobit/releases/tag/v1.0.2-52-helium-syncrobit-2023-07-23-OpenFleet

**Comment by WayneNebra** [comment]
@Dmoss1976 Please create a ticket and let me know or share the serial number or the MAC address in here if you like, and also, as crazy as it sounds you have connected the antenna from the LoRa concentrator to the correct internal IPX connection, I've seen it on help desk where people have connected it to the WIFI pin inside the machine, this is if you actually removed it in the 1st place of course.

**Comment by Dmoss1976** [comment]
> This was the image you downloaded? https://github.com/NebraLtd/helium-syncrobit/releases/tag/v1.0.2-52-helium-syncrobit-2023-07-23-OpenFleet

Yes

**Comment by WayneNebra** [comment]
@Dmoss1976 Can you write that to an SD card using Balena Etcher please, use a Samsung SanDisk Extreme Pro or something along the lines, something with a fast read/write speed. 

Then place it in the miner and boot it, can you then see if you can get to local diagnostics. (Use it's IP address in your browser)

**Comment by Dmoss1976** [comment]
Sorted. Needed a new u.fl cable

**Comment by shawaj** [comment]
Awesome thanks for the update
