### ISSUE TITLE
Unable to deploy in balena cloud 

### ISSUE THREAD

**Issue by MihaiDoro** [NebraLtd/helium-syncrobit#22]
When I try to deploy latest release for my Syncrobit I get these errors. 
![Screenshot_2023-08-12-22-59-51-43_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/NebraLtd/helium-syncrobit/assets/128918842/ee7de026-1f5c-4e45-9940-41eb934a288a)
`

**Comment by shawaj** [comment]
You probably need to contact Balena about this. Not something we can help with.

The release works fine. Their must be an error with your fleet
