### ISSUE TITLE
missing change inside dockey_compose.yml

### ISSUE THREAD

**Issue by chapy23** [NebraLtd/helium-syncrobit#8]
I think there is small mistake in the dockey_compose.yml
someone forgot to change the release there,   
TEST-helium-syncrobit-2023-03-20-OpenFleet  after flashing, we are seeing:  2023.02.07.0-23 (65b1d88)
but in the docker_compose.yml push trough un Balena Cloud update, i still can see 2023.02.07.0-16 (65b1d88)

![proof_docker_compose yml](https://user-images.githubusercontent.com/11875678/227330496-20488ec0-c8d2-4c26-a7e2-d25f7c9011e3.jpg)

**Comment by shawaj** [comment]
We don't update anything via BalenaCloud. So where are you seeing this?

**Comment by vstrong-info** [comment]
> We don't update anything via BalenaCloud. So where are you seeing this?
What is the right way to update miners deployed via BalenaCloud? We noticed they do not get updated automatically OTA.

**Comment by chapy23** [comment]
[cid:99aebd02-1e48-4d20-a927-ebafb2ff2922]

open the docker_compose.yml

[cid:4b2c069f-df2d-441b-9e8d-0f7ccd454117]
________________________________
De : Aaron Shaw ***@***.***>
Envoyé : 23 mars 2023 18:31
À : NebraLtd/helium-syncrobit ***@***.***>
Cc : chapy23 ***@***.***>; Author ***@***.***>
Objet : Re: [NebraLtd/helium-syncrobit] missing change inside dockey_compose.yml (Issue #8)


We don't update anything via BalenaCloud. So where are you seeing this?

**Comment by shawaj** [comment]
No idea what you are talking about. The open Fleet images are generated from this repo so they are based on the existing docker compose in this repo.

But yes, if you deploy yourself via BalenaCloud then you will not get OTA updates and will have to manually update yourself. 

If you use the OpenFleet images you will get OTA updates.

**Comment by shawaj** [comment]
Just as an additional note, the OpenFleets will get updated always before an updated docker compose gets pushed to this repo.

The reason for this is that that is how our production workflows operate. The update gets pushed to our open fleet, then the action in this repo tries to generate an updated image from the open fleet.

Only if the above steps are successful does the docker compose update get pushed to this repo.

You are able to get more quick updates if you generate the docker compose yourself on the fly from our upstream repo at https://github.com/NebraLtd/helium-miner-software

But this would be a lot more involved and you would need to have a fair bit of technical knowledge to do this. It's also something that you would need to work out yourself

**Comment by chapy23** [comment]
I was thinking that Balena Cloud was connect directly to the github of Helium-SyncroBit.  So thank's for clarifying that.

The problem was the version .19,  we were stuck there and did not receive OTA to go at .23
So everyone was flashing manually .23,  so i decide to look for a workaround to next time flash remotely with Balena Cloud.

Can you confirm that from .19, going to .23 was not possible or maybe it will be fix soon ?

bye

Martin C.
________________________________
De : Aaron Shaw ***@***.***>
Envoyé : 23 mars 2023 18:54
À : NebraLtd/helium-syncrobit ***@***.***>
Cc : chapy23 ***@***.***>; Author ***@***.***>
Objet : Re: [NebraLtd/helium-syncrobit] missing change inside dockey_compose.yml (Issue #8)


Just as an additional note, the OpenFleets will get updated always before an updated docker compose gets pushed to this repo.

The reason for this is that that is how our production workflows operate. The update gets pushed to our open fleet, then the action in this repo tries to generate an updated image from the open fleet.

Only if the above steps are successful does the docker compose update get pushed to this repo.

You are able to get more quick updates if you generate the docker compose yourself on the fly from our upstream repo at https://github.com/NebraLtd/helium-miner-software

But this would be a lot more involved and you would need to have a fair bit of technical knowledge to do this. It's also something that you would need to work out yourself

**Comment by shawaj** [comment]
@chapy23 the -19 release was broken accidentally.

So you will need to manually flash to one of the releases mentioned in this comment:
https://github.com/NebraLtd/helium-syncrobit/issues/2#issuecomment-1482037237

After that the OTA should work on our fleets.

For BalenaCloud installation, each time there is a new release you would need to click the "deploy with Balena" button and select to push the new release to your existing fleet on BalenaCloud. Alternatively, you could set up your own GitHub repo that automatically clones ours when there is a new release and pushes the update automatically to your BalenaCloud fleet. But this requires a fair bit of technical knowledge, but does give you more flexibility and control over the devices. So it's up to you really 😉

**Comment by shawaj** [comment]
This is how you add to an existing fleet on Balena...

![Screenshot_20230324_132456_Chrome](https://user-images.githubusercontent.com/3359418/227533971-e405eee7-e8a9-49bc-b645-3310f0b09a0c.jpg)
![Screenshot_20230324_132522_Chrome](https://user-images.githubusercontent.com/3359418/227534351-fbd4680b-95f8-4747-9e60-56b6861e45da.jpg)

You can toggle the advanced selector but just leave the settings as default

**Comment by chapy23** [comment]
Thank's for all those details, i appreciate it.
i'm not a developper,   i work in cybersecurity, so   🙂

i just saw this morning the update on the for .25 release, but as you explain to me, some file will be update later, like this one

[cid:7d43b0ed-0601-44fe-953b-94062cc95506]

I was using that file, download it, uncompressed and push it using Balena CLI.
I will try what you explain to me using "existing fleet"

continue your good work and thank's again to take care of our suppose to be now DEAD Syncrobit   🙂

bye
________________________________
De : Aaron Shaw ***@***.***>
Envoyé : 24 mars 2023 09:31
À : NebraLtd/helium-syncrobit ***@***.***>
Cc : chapy23 ***@***.***>; Mention ***@***.***>
Objet : Re: [NebraLtd/helium-syncrobit] missing change inside dockey_compose.yml (Issue #8)


This is how you add to an existing fleet on Balena...

[Screenshot_20230324_132456_Chrome]<https://user-images.githubusercontent.com/3359418/227533971-e405eee7-e8a9-49bc-b645-3310f0b09a0c.jpg>
[Screenshot_20230324_132522_Chrome]<https://user-images.githubusercontent.com/3359418/227534351-fbd4680b-95f8-4747-9e60-56b6861e45da.jpg>

You can toggle the advanced selector but just leave the settings as default
